<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>se.mdu</groupId>
    <artifactId>mdu-oss-parent</artifactId>
    <version>67</version>
    <relativePath>../mdu-oss-parent/pom.xml</relativePath>
  </parent>

  <groupId>se.mdu.driftavbrott</groupId>
  <artifactId>mdu-driftavbrott-facade</artifactId>
  <version>4.0.0-SNAPSHOT</version>

  <name>${project.groupId}:${project.artifactId}</name>
  <description>En klient som pratar med driftavbrottstjänstens web service.</description>
  <url>https://github.com/mdh-se/${project.artifactId}</url>

  <scm>
    <connection>scm:git:https://github.com/mdh-se/${project.artifactId}.git</connection>
    <developerConnection>scm:git:https://github.com/mdh-se/${project.artifactId}.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/mdh-se/${project.artifactId}</url>
  </scm>

  <properties>
    <mdh.driftavbrott.service.url>${mdh.driftavbrott.service.base.url}:3301/mdh-driftavbrott/v1</mdh.driftavbrott.service.url>
    <mdh.cxf.version>4.2.2</mdh.cxf.version>
    <mdh.jakarta.annotation-api.version>3.0.0</mdh.jakarta.annotation-api.version>
    <mdh.jakarta.ws.rs-api.version>4.0.0</mdh.jakarta.ws.rs-api.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.15.0</version>
    </dependency>
    <dependency>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.ws.rs</groupId>
      <artifactId>jakarta.ws.rs-api</artifactId>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.cxf</groupId>
      <artifactId>cxf-rt-rs-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- Styr logging från Commons Logging API till Log4J 2 -->
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-jcl</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- Styr om logging från SLF4J API till Log4J 2 -->
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j-impl</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>se.mdu.driftavbrott</groupId>
      <artifactId>mdu-driftavbrott-modell</artifactId>
      <version>1.7.0</version>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-release-plugin</artifactId>
          <configuration>
            <releaseProfiles>changes,mdh-release</releaseProfiles>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <profiles>
    <profile>
      <!--
        Dessa tester ligger i en profil som måste aktiveras manuellt, eftersom
        de kopplar upp sig mot web services, som inte alltid går att nå. För att
        köra dessa integrationstester måste du också ange propertyn
        mdh.driftavbrott.service.base.url som skall peka ut den bas-URL där
        driftavbrottstjänsten är installerad, till exempel:
        -Prun-its -Dmdh.driftavbrott.service.base.url=http://localhost
      -->
      <id>run-its</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-failsafe-plugin</artifactId>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
